Container Monitor: SQLiteDatabase Class Reference
SQLiteDatabase Class Reference
SQLite implementation of the IDatabaseInterface.
#include <sqlite_database.hpp>
Public Member Functions
SQLiteDatabase (const std::string &db_path)
Constructs a SQLiteDatabase and opens the database file.
~SQLiteDatabase ()
Destructor. Closes the database connection.
void saveContainer (const std::string &name, const ContainerInfo &info) override
Saves container information to the database and cache.
void removeContainer (const std::string &name) override
Removes a container from the database and cache.
void clearAll () override
Clears all tables and cached data in the database.
ContainerInfo getContainer (const std::string &name) const override
Retrieves container information by name from the cache.
size_t size () const override
Returns the number of containers in the cache.
const std::map< std::string, ContainerInfo > & getAll () const override
Returns all container information from the cache.
void setupSchema () override
Sets up the database schema (tables).
void insertBatch (const std::string &container_name, const std::vector< ContainerMetrics > &metrics_vec) override
Inserts a batch of metrics for a container.
void exportAllTablesToCSV (const std::string &export_dir) override
Exports all tables to CSV files in the specified directory.
void saveHostUsage (int64_t timestamp_ms, double cpu_usage_percent, double mem_usage_percent) override
Saves host usage metrics to the database.
Public Member Functions inherited from IDatabaseInterface
virtual ~IDatabaseInterface ()=default
Detailed Description
SQLite implementation of the IDatabaseInterface.
Manages container and host usage data using SQLite, supports batch inserts, schema setup, CSV export, and thread-safe access.
Definition at line 22 of file sqlite_database.hpp.
Constructor & Destructor Documentation
SQLiteDatabase()
SQLiteDatabase::SQLiteDatabase (const std::string & db_path)
Constructs a SQLiteDatabase and opens the database file.
Parameters
db_path Path to the SQLite database file.
Definition at line 16 of file sqlite_database.cpp.
                                                        : db_(nullptr) {
     if (sqlite3_open(db_path.c_str(), &db_) != SQLITE_OK) {
         CM_LOG_ERROR << "Failed to open SQLite database: " << db_path << "\n";
         db_ = nullptr;
     }
 }
References CM_LOG_ERROR.
~SQLiteDatabase()
SQLiteDatabase::~SQLiteDatabase ()
Destructor. Closes the database connection.
Definition at line 26 of file sqlite_database.cpp.
{
     if (db_) sqlite3_close(db_);
 }
Member Function Documentation
clearAll()
void SQLiteDatabase::clearAll () override virtual
Clears all tables and cached data in the database.
Implements IDatabaseInterface.
Definition at line 123 of file sqlite_database.cpp.
{
     if (!db_) return;
     const char* sql1 = SQL_DELETE_ALL_CONTAINERS;
     const char* sql2 = SQL_DELETE_CONTAINER_METRICS;
     const char* sql3 = SQL_DELETE_HOST_USAGE;
     char* err_msg = nullptr;
     if (sqlite3_exec(db_, sql1, nullptr, nullptr, &err_msg) != SQLITE_OK) {
         CM_LOG_ERROR << "Failed to clear containers table: " << (err_msg ? err_msg : "unknown error") << "\n";
         sqlite3_free(err_msg);
     }
     if (sqlite3_exec(db_, sql2, nullptr, nullptr, &err_msg) != SQLITE_OK) {
         CM_LOG_ERROR << "Failed to clear container_metrics table: " << (err_msg ? err_msg : "unknown error") << "\n";
         sqlite3_free(err_msg);
     }
     if (sqlite3_exec(db_, sql3, nullptr, nullptr, &err_msg) != SQLITE_OK) {
         CM_LOG_ERROR << "Failed to clear host_usage table: " << (err_msg ? err_msg : "unknown error") << "\n";
         sqlite3_free(err_msg);
     }
     cache_.clear();
 }
References CM_LOG_ERROR, SQL_DELETE_ALL_CONTAINERS, SQL_DELETE_CONTAINER_METRICS, and SQL_DELETE_HOST_USAGE.
Referenced by main().
exportAllTablesToCSV()
void SQLiteDatabase::exportAllTablesToCSV (const std::string & export_dir) override virtual
Exports all tables to CSV files in the specified directory.
Parameters
export_dir Directory to export CSV files.
Implements IDatabaseInterface.
Definition at line 202 of file sqlite_database.cpp.
{
     std::lock_guard<std::mutex> lock(db_mutex);
     std::filesystem::create_directories(export_dir);
     // Export container_metrics table
     {
         std::string filename = export_dir + CSV_CONTAINER_METRICS_FILENAME;
         std::ofstream file(filename);
         if (!file.is_open()) {
             CM_LOG_ERROR << "Failed to open container_metrics.csv for export: " << filename << "\n";
         } else {
             file << CSV_CONTAINER_METRICS_HEADER;
             const char* sql = SQL_SELECT_CONTAINER_METRICS;
             sqlite3_stmt* stmt;
             if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) == SQLITE_OK) {
                 while (sqlite3_step(stmt) == SQLITE_ROW) {
                     file << reinterpret_cast<const char*>(sqlite3_column_text(stmt, 0)) << ",";
                     file << sqlite3_column_int64(stmt, 1) << ",";
                     file << sqlite3_column_double(stmt, 2) << ",";
                     file << sqlite3_column_double(stmt, 3) << ",";
                     file << sqlite3_column_double(stmt, 4) << "\n";
                 }
                 sqlite3_finalize(stmt);
             } else {
                 CM_LOG_ERROR << "Failed to prepare export SQL for container_metrics: " << sqlite3_errmsg(db_) << "\n";
             }
             file.close();
         }
     }
     // Export host_usage table
     {
         std::string filename = export_dir + CSV_HOST_USAGE_FILENAME;
         std::ofstream file(filename);
         if (!file.is_open()) {
             CM_LOG_ERROR << "Failed to open host_usage.csv for export: " << filename << "\n";
         } else {
             file << CSV_HOST_USAGE_HEADER;
             const char* sql = SQL_SELECT_HOST_USAGE;
             sqlite3_stmt* stmt;
             if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) == SQLITE_OK) {
                 while (sqlite3_step(stmt) == SQLITE_ROW) {
                     file << sqlite3_column_int64(stmt, 0) << ",";
                     file << sqlite3_column_double(stmt, 1) << ",";
                     file << sqlite3_column_int64(stmt, 2) << "\n";
                 }
                 sqlite3_finalize(stmt);
             }
             file.close();
         }
     }
 }
References CM_LOG_ERROR, CSV_CONTAINER_METRICS_FILENAME, CSV_CONTAINER_METRICS_HEADER, CSV_HOST_USAGE_FILENAME, SQL_SELECT_CONTAINER_METRICS, and SQL_SELECT_HOST_USAGE.
Referenced by main().
getAll()
const std::map< std::string, ContainerInfo > & SQLiteDatabase::getAll () const override virtual
Returns all container information from the cache.
Returns
Map of container name to ContainerInfo.
Implements IDatabaseInterface.
Definition at line 77 of file sqlite_database.cpp.
{
     loadCache();
     return cache_;
 }
getContainer()
ContainerInfo SQLiteDatabase::getContainer (const std::string & name) const override virtual
Retrieves container information by name from the cache.
Parameters
name Container name.
Returns
ContainerInfo struct.
Implements IDatabaseInterface.
Definition at line 56 of file sqlite_database.cpp.
{
     if (!db_) return {};
     loadCache();
     auto it = cache_.find(name);
     if (it != cache_.end()) return it->second;
     return {};
 }
insertBatch()
void SQLiteDatabase::insertBatch (const std::string & container_name, const std::vector< ContainerMetrics > & metrics_vec) override virtual
Inserts a batch of metrics for a container.
Parameters
container_name Container name.
metrics_vec Vector of ContainerMetrics.
Implements IDatabaseInterface.
Definition at line 179 of file sqlite_database.cpp.
{
     std::lock_guard<std::mutex> lock(db_mutex);
     if (!db_ || metrics_vec.empty()) return;
     const char* sql = SQL_INSERT_CONTAINER_METRICS;
     sqlite3_stmt* stmt;
     if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) == SQLITE_OK) {
         for (const auto& metrics : metrics_vec) {
             sqlite3_bind_text(stmt, 1, container_name.c_str(), -1, SQLITE_TRANSIENT);
             sqlite3_bind_int64(stmt, 2, metrics.timestamp);
             sqlite3_bind_double(stmt, 3, metrics.cpu_usage_percent);
             sqlite3_bind_double(stmt, 4, metrics.memory_usage_percent);
             sqlite3_bind_double(stmt, 5, metrics.pids_percent);
             sqlite3_step(stmt);
             sqlite3_reset(stmt);
         }
         sqlite3_finalize(stmt);
     }
 }
References SQL_INSERT_CONTAINER_METRICS.
removeContainer()
void SQLiteDatabase::removeContainer (const std::string & name) override virtual
Removes a container from the database and cache.
Parameters
name Container name.
Implements IDatabaseInterface.
Definition at line 108 of file sqlite_database.cpp.
{
     if (!db_) return;
     const char* sql = SQL_DELETE_CONTAINER_BY_NAME;
     sqlite3_stmt* stmt;
     if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) == SQLITE_OK) {
         sqlite3_bind_text(stmt, 1, name.c_str(), -1, SQLITE_TRANSIENT);
         sqlite3_step(stmt);
         sqlite3_finalize(stmt);
     }
     cache_.erase(name);
 }
References SQL_DELETE_CONTAINER_BY_NAME.
saveContainer()
void SQLiteDatabase::saveContainer (const std::string & name, const ContainerInfo & info) override virtual
Saves container information to the database and cache.
Parameters
name Container name.
info ContainerInfo struct.
Implements IDatabaseInterface.
Definition at line 35 of file sqlite_database.cpp.
{
     if (!db_) return;
     const char* sql = SQL_INSERT_OR_REPLACE_CONTAINER;
     sqlite3_stmt* stmt;
     if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) == SQLITE_OK) {
         sqlite3_bind_text(stmt, 1, name.c_str(), -1, SQLITE_TRANSIENT);
         sqlite3_bind_text(stmt, 2, info.id.c_str(), -1, SQLITE_TRANSIENT);
         sqlite3_bind_double(stmt, 3, info.cpu_limit);
         sqlite3_bind_int(stmt, 4, info.memory_limit);
         sqlite3_bind_int(stmt, 5, info.pid_limit);
         sqlite3_step(stmt);
         sqlite3_finalize(stmt);
     }
     cache_[name] = info;
 }
References ContainerInfo::cpu_limit, ContainerInfo::id, ContainerInfo::memory_limit, ContainerInfo::pid_limit, and SQL_INSERT_OR_REPLACE_CONTAINER.
saveHostUsage()
void SQLiteDatabase::saveHostUsage (int64_t timestamp_ms, double cpu_usage_percent, double mem_usage_percent) override virtual
Saves host usage metrics to the database.
Parameters
timestamp_ms Timestamp in milliseconds.
cpu_usage_percent CPU usage percent.
mem_usage_percent Memory usage percent.
Implements IDatabaseInterface.
Definition at line 261 of file sqlite_database.cpp.
{
     if (!db_) return;
     const char* sql = SQL_INSERT_HOST_USAGE;
     sqlite3_stmt* stmt;
     if (sqlite3_prepare_v2(db_, sql, -1, &stmt, nullptr) == SQLITE_OK) {
         sqlite3_bind_int64(stmt, 1, timestamp_ms);
         sqlite3_bind_double(stmt, 2, cpu_usage_percent);
         sqlite3_bind_double(stmt, 3, mem_usage_percent);
         sqlite3_step(stmt);
         sqlite3_finalize(stmt);
     }
 }
References SQL_INSERT_HOST_USAGE.
setupSchema()
void SQLiteDatabase::setupSchema () override virtual
Sets up the database schema (tables).
Implements IDatabaseInterface.
Definition at line 147 of file sqlite_database.cpp.
{
     // Create containers table
     const char* create_containers_sql = SQL_CREATE_CONTAINERS_TABLE;
     char* errMsg = nullptr;
     int rc = sqlite3_exec(db_, create_containers_sql, nullptr, nullptr, &errMsg);
     if (rc != SQLITE_OK) {
         CM_LOG_ERROR << "Failed to create containers table: " << errMsg << "\n";
         sqlite3_free(errMsg);
     }
     // Create container_metrics table
     const char* create_container_metrics_sql = SQL_CREATE_CONTAINER_METRICS_TABLE;
     rc = sqlite3_exec(db_, create_container_metrics_sql, nullptr, nullptr, &errMsg);
     if (rc != SQLITE_OK) {
         CM_LOG_ERROR << "Failed to create container_metrics table: " << errMsg << "\n";
         sqlite3_free(errMsg);
     }
     // Create host_usage table
     const char* create_host_usage_sql = SQL_CREATE_HOST_USAGE_TABLE;
     rc = sqlite3_exec(db_, create_host_usage_sql, nullptr, nullptr, &errMsg);
     if (rc != SQLITE_OK) {
         CM_LOG_ERROR << "Failed to create host_usage table: " << errMsg << "\n";
         sqlite3_free(errMsg);
     }
 }
References CM_LOG_ERROR, SQL_CREATE_CONTAINER_METRICS_TABLE, SQL_CREATE_CONTAINERS_TABLE, and SQL_CREATE_HOST_USAGE_TABLE.
Referenced by main().
size()
size_t SQLiteDatabase::size () const override virtual
Returns the number of containers in the cache.
Returns
Number of containers.
Implements IDatabaseInterface.
Definition at line 68 of file sqlite_database.cpp.
{
     loadCache();
     return cache_.size();
 }
The documentation for this class was generated from the following files:
database/inc/sqlite_database.hpp
database/src/sqlite_database.cpp