Container Monitor: EventProcessor Class Reference
EventProcessor Class Reference
Processes container events and periodically collects host metrics.
#include <event_processor.hpp>
Public Member Functions
EventProcessor (EventQueue &queue, std::atomic< bool > &shutdown_flag, IDatabaseInterface &db, const MonitorConfig &cfg)
Constructs an EventProcessor.
~EventProcessor ()
Destructor. Ensures the worker thread is stopped.
void start ()
Starts the event processor thread.
void stop ()
Stops the event processor thread.
Detailed Description
Processes container events and periodically collects host metrics.
Runs in a separate thread, pops events from the event queue, parses them, updates the database, and collects host resource usage at regular intervals.
Definition at line 22 of file event_processor.hpp.
Constructor & Destructor Documentation
EventProcessor()
EventProcessor::EventProcessor (EventQueue & queue, std::atomic< bool > & shutdown_flag, IDatabaseInterface & db, const MonitorConfig & cfg)
Constructs an EventProcessor.
Parameters
queue Reference to the event queue.
shutdown_flag Reference to the application's shutdown flag.
db Reference to the database interface.
cfg Reference to the monitor configuration.
Definition at line 19 of file event_processor.cpp.
     : queue_(queue), shutdown_flag_(shutdown_flag), db_(db), cfg_(cfg) {}
~EventProcessor()
EventProcessor::~EventProcessor ()
Destructor. Ensures the worker thread is stopped.
Definition at line 25 of file event_processor.cpp.
 { stop(); }
References stop().
Member Function Documentation
start()
void EventProcessor::start ()
Starts the event processor thread.
Definition at line 30 of file event_processor.cpp.
{
     running_ = true;
     worker_ = std::thread(&EventProcessor::processLoop, this);
 }
stop()
void EventProcessor::stop ()
Stops the event processor thread.
Definition at line 38 of file event_processor.cpp.
{
     running_ = false;
     queue_.shutdown();
     if (worker_.joinable()) worker_.join();
 }
References EventQueue::shutdown().
Referenced by ~EventProcessor().
The documentation for this class was generated from the following files:
monitoring_service/inc/event_processor.hpp
monitoring_service/src/event_processor.cpp