Container Monitor: ResourceThreadPool Class Reference
ResourceThreadPool Class Reference
Manages a pool of threads for collecting container resource metrics in parallel.
#include <resource_thread_pool.hpp>
Public Member Functions
ResourceThreadPool (const MonitorConfig &cfg, std::atomic< bool > &shutdown_flag, IDatabaseInterface &db)
Constructs a ResourceThreadPool.
~ResourceThreadPool ()
Destructor. Ensures all threads are stopped and buffers flushed.
void start ()
Starts all worker threads.
void stop ()
Stops all worker threads and flushes buffers.
void addContainer (const std::string &name)
Adds a container to the thread pool for monitoring.
void removeContainer (const std::string &name)
Removes a container from the thread pool.
void flushAllBuffers ()
Flushes all metric buffers to the database.
std::map< int, std::vector< std::string > > getAssignments ()
Gets the current thread-to-container assignments.
Detailed Description
Manages a pool of threads for collecting container resource metrics in parallel.
Assigns containers to threads, collects metrics, batches data for database insertion, and sends max metrics to the UI via message queue.
Definition at line 26 of file resource_thread_pool.hpp.
Constructor & Destructor Documentation
ResourceThreadPool()
ResourceThreadPool::ResourceThreadPool (const MonitorConfig & cfg, std::atomic< bool > & shutdown_flag, IDatabaseInterface & db)
Constructs a ResourceThreadPool.
Parameters
cfg Monitor configuration.
shutdown_flag Reference to the application's shutdown flag.
db Reference to the database interface.
Definition at line 29 of file resource_thread_pool.cpp.
     : cfg_(cfg), shutdown_flag_(shutdown_flag), db_(db), thread_containers_(cfg.thread_count),
       thread_buffers_(cfg.thread_count), thread_local_paths_(cfg.thread_count), thread_local_info_(cfg.thread_count)
 {
     // Initialize the factory once
     if (cfg_.runtime == "docker" && cfg_.cgroup == "v1") {
         pathFactory_ = std::make_unique<DockerCgroupV1PathFactory>();
     }
 }
References MonitorConfig::cgroup, and MonitorConfig::runtime.
~ResourceThreadPool()
ResourceThreadPool::~ResourceThreadPool ()
Destructor. Ensures all threads are stopped and buffers flushed.
Definition at line 42 of file resource_thread_pool.cpp.
{
     stop();
 }
References stop().
Member Function Documentation
addContainer()
void ResourceThreadPool::addContainer (const std::string & name)
Adds a container to the thread pool for monitoring.
Parameters
name Container name.
Definition at line 72 of file resource_thread_pool.cpp.
{
     std::unique_lock<std::mutex> lock(assign_mutex_);
     flushAllBuffers();
     int min_thread = -1, min_load = cfg_.thread_capacity + 1;
     for (int i = 0; i < cfg_.thread_count; ++i) {
         if (thread_containers_[i].size() < cfg_.thread_capacity && thread_containers_[i].size() < min_load) {
             min_thread = i;
             min_load = thread_containers_[i].size();
         }
     }
     if (min_thread == -1) {
         CM_LOG_INFO << "[ThreadPool] Capacity full, cannot assign container: " << name << "\n";
         return;
     }
     thread_containers_[min_thread].push_back(name);
     container_to_thread_[name] = min_thread;
     // Fetch full container info from database
     ContainerInfo info = db_.getContainer(name);
     thread_local_info_[min_thread][name] = info;
     ContainerResourcePaths paths = pathFactory_->getPaths(info.id);
     thread_local_paths_[min_thread][name] = paths;
     CM_LOG_INFO << "[ThreadPool] Paths for container " << name << ":\n"
                 << "  CPU: " << paths.cpu_path << "\n"
                 << "  Memory: " << paths.memory_path << "\n"
                 << "  PIDs: " << paths.pids_path << "\n";
     CM_LOG_INFO << "[ThreadPool] Assigned container " << name << " to thread " << min_thread << "\n";
     cv_.notify_all();
 }
References CM_LOG_INFO, ContainerResourcePaths::cpu_path, flushAllBuffers(), IDatabaseInterface::getContainer(), ContainerInfo::id, ContainerResourcePaths::memory_path, ContainerResourcePaths::pids_path, MonitorConfig::thread_capacity, and MonitorConfig::thread_count.
flushAllBuffers()
void ResourceThreadPool::flushAllBuffers ()
Flushes all metric buffers to the database.
Definition at line 127 of file resource_thread_pool.cpp.
{
     for (int i = 0; i < cfg_.thread_count; ++i) {
         auto& buffers = thread_buffers_[i];
         for (auto& [name, buffer] : buffers) {
             if (!buffer.empty()) db_.insertBatch(name, buffer);
             buffer.clear();
         }
     }
 }
References IDatabaseInterface::insertBatch(), and MonitorConfig::thread_count.
Referenced by addContainer(), removeContainer(), and stop().
getAssignments()
std::map< int, std::vector< std::string > > ResourceThreadPool::getAssignments ()
Gets the current thread-to-container assignments.
Returns
Map of thread index to vector of container names.
Definition at line 141 of file resource_thread_pool.cpp.
{
     std::unique_lock<std::mutex> lock(assign_mutex_);
     std::map<int, std::vector<std::string>> result;
     for (int i = 0; i < cfg_.thread_count; ++i) {
         result[i] = thread_containers_[i];
     }
     return result;
 }
References MonitorConfig::thread_count.
removeContainer()
void ResourceThreadPool::removeContainer (const std::string & name)
Removes a container from the thread pool.
Parameters
name Container name.
Definition at line 108 of file resource_thread_pool.cpp.
{
     std::unique_lock<std::mutex> lock(assign_mutex_);
     flushAllBuffers();
     auto it = container_to_thread_.find(name);
     if (it != container_to_thread_.end()) {
         int thread_idx = it->second;
         auto& vec = thread_containers_[thread_idx];
         vec.erase(std::remove(vec.begin(), vec.end(), name), vec.end());
         container_to_thread_.erase(it);
         thread_local_info_[thread_idx].erase(name);
         thread_local_paths_[thread_idx].erase(name);
         CM_LOG_INFO << "[ThreadPool] Removed container " << name << " from thread " << thread_idx << "\n";
         cv_.notify_all();
     }
 }
References CM_LOG_INFO, and flushAllBuffers().
start()
void ResourceThreadPool::start ()
Starts all worker threads.
Definition at line 49 of file resource_thread_pool.cpp.
{
     running_ = true;
     for (int i = 0; i < cfg_.thread_count; ++i) {
         threads_.emplace_back([this, i]() { workerLoop(i); });
     }
 }
References MonitorConfig::thread_count.
Referenced by main().
stop()
void ResourceThreadPool::stop ()
Stops all worker threads and flushes buffers.
Definition at line 59 of file resource_thread_pool.cpp.
{
     running_ = false;
     cv_.notify_all();
     flushAllBuffers();
     for (auto& t : threads_) {
         if (t.joinable()) t.join();
     }
 }
References flushAllBuffers().
Referenced by main(), and ~ResourceThreadPool().
The documentation for this class was generated from the following files:
monitoring_service/inc/resource_thread_pool.hpp
monitoring_service/src/resource_thread_pool.cpp