Container Monitor: LiveMetricAggregator Class Reference
LiveMetricAggregator Class Reference
Aggregates live container metrics from a POSIX message queue and updates the dashboard.
#include <live_metric_aggregator.hpp>
Public Member Functions
LiveMetricAggregator (std::atomic< bool > &shutdown_flag, MonitorDashboard *dashboard, int ui_refresh_interval_ms)
Constructs a LiveMetricAggregator.
~LiveMetricAggregator ()
Destructor. Ensures the worker thread is stopped.
void start ()
Starts the aggregator thread.
void stop ()
Stops the aggregator thread.
Detailed Description
Aggregates live container metrics from a POSIX message queue and updates the dashboard.
Periodically reads messages containing container metrics, updates the dashboard, and removes stale containers based on the UI refresh interval.
Definition at line 20 of file live_metric_aggregator.hpp.
Constructor & Destructor Documentation
LiveMetricAggregator()
LiveMetricAggregator::LiveMetricAggregator (std::atomic< bool > & shutdown_flag, MonitorDashboard * dashboard, int ui_refresh_interval_ms)
Constructs a LiveMetricAggregator.
Parameters
shutdown_flag Reference to the application's shutdown flag.
dashboard Pointer to the MonitorDashboard instance.
ui_refresh_interval_ms UI refresh interval in milliseconds.
Definition at line 23 of file live_metric_aggregator.cpp.
     : shutdown_flag_(shutdown_flag), dashboard_(dashboard), ui_refresh_interval_ms_(ui_refresh_interval_ms) {}
~LiveMetricAggregator()
LiveMetricAggregator::~LiveMetricAggregator ()
Destructor. Ensures the worker thread is stopped.
Definition at line 29 of file live_metric_aggregator.cpp.
{
     stop();
 }
References stop().
Member Function Documentation
start()
void LiveMetricAggregator::start ()
Starts the aggregator thread.
Definition at line 36 of file live_metric_aggregator.cpp.
{
     if (!running_) {
         running_ = true;
         worker_ = std::thread(&LiveMetricAggregator::run, this);
     }
 }
Referenced by main().
stop()
void LiveMetricAggregator::stop ()
Stops the aggregator thread.
Definition at line 46 of file live_metric_aggregator.cpp.
{
     running_ = false;
     if (worker_.joinable()) {
         worker_.join();
     }
 }
Referenced by main(), and ~LiveMetricAggregator().
The documentation for this class was generated from the following files:
analysis/inc/live_metric_aggregator.hpp
analysis/src/live_metric_aggregator.cpp