Container Monitor: MonitorDashboard Class Reference
MonitorDashboard Class Reference
Displays live container metrics in a color-coded ncurses UI.
#include <monitor_dashboard.hpp>
Public Member Functions
MonitorDashboard (std::atomic< bool > &shutdown_flag, const MonitorConfig &cfg)
Constructs a MonitorDashboard.
~MonitorDashboard ()
Destructor. Ensures the UI thread is stopped.
void pushMetrics (const ContainerMaxMetricsMsg &metrics)
Pushes new metrics for a container.
void pushMetricsRemoved (const std::string &container_id)
Removes metrics for a container.
void start ()
Starts the dashboard UI thread.
void stop ()
Stops the dashboard UI thread.
Detailed Description
Displays live container metrics in a color-coded ncurses UI.
Receives metrics via message queue, updates the display, and removes stale containers. Supports dynamic column alignment and color coding based on alert thresholds.
Definition at line 32 of file monitor_dashboard.hpp.
Constructor & Destructor Documentation
MonitorDashboard()
MonitorDashboard::MonitorDashboard (std::atomic< bool > & shutdown_flag, const MonitorConfig & cfg)
Constructs a MonitorDashboard.
Parameters
shutdown_flag Reference to the application's shutdown flag.
cfg Reference to monitor configuration.
Definition at line 19 of file monitor_dashboard.cpp.
     : shutdown_flag_(shutdown_flag), cfg_(cfg) {
     CM_LOG_INFO << "[MonitorDashboard] ui_refresh_interval_ms_: " << cfg_.ui_refresh_interval_ms << "\n";
 }
References CM_LOG_INFO, and MonitorConfig::ui_refresh_interval_ms.
~MonitorDashboard()
MonitorDashboard::~MonitorDashboard ()
Destructor. Ensures the UI thread is stopped.
Definition at line 27 of file monitor_dashboard.cpp.
{
     stop();
 }
References stop().
Member Function Documentation
pushMetrics()
void MonitorDashboard::pushMetrics (const ContainerMaxMetricsMsg & metrics)
Pushes new metrics for a container.
Parameters
metrics ContainerMaxMetricsMsg struct.
Definition at line 35 of file monitor_dashboard.cpp.
{
     int64_t now = std::chrono::duration_cast<std::chrono::milliseconds>(
         std::chrono::system_clock::now().time_since_epoch()).count();
     {
         std::lock_guard<std::mutex> lock(data_mutex_);
         CM_LOG_INFO << "[MonitorDashboard] pushMetrics: " << metrics.container_id
                     << " | CPU: " << metrics.max_cpu_usage_percent
                     << " | Mem: " << metrics.max_memory_usage_percent
                     << " | PIDs: " << metrics.max_pids_percent << "\n";
         // Check if container already exists, update if found, else append
         bool found = false;
         for (auto& entry : metrics_vec_) {
             if (entry.container_id == metrics.container_id) {
                 entry.metrics = metrics;
                 entry.timestamp = now;
                 found = true;
                 break;
             }
         }
         if (!found) {
             metrics_vec_.push_back({metrics.container_id, metrics, now});
         }
         data_updated_ = true;
     }
     data_cv_.notify_one();
 }
References CM_LOG_INFO, ContainerMaxMetricsMsg::container_id, ContainerMaxMetricsMsg::max_cpu_usage_percent, ContainerMaxMetricsMsg::max_memory_usage_percent, and ContainerMaxMetricsMsg::max_pids_percent.
pushMetricsRemoved()
void MonitorDashboard::pushMetricsRemoved (const std::string & container_id)
Removes metrics for a container.
Parameters
container_id Container identifier.
Definition at line 66 of file monitor_dashboard.cpp.
{
     {
         std::lock_guard<std::mutex> lock(data_mutex_);
         auto it = std::remove_if(metrics_vec_.begin(), metrics_vec_.end(),
                                  [&](const ContainerMetricsEntry& entry) {
                                      return entry.container_id == container_id;
                                  });
         if (it != metrics_vec_.end()) {
             metrics_vec_.erase(it, metrics_vec_.end());
             CM_LOG_INFO << "[MonitorDashboard] pushMetricsRemoved: " << container_id << "\n";
             data_updated_ = true;
         } else {
             CM_LOG_INFO << "[MonitorDashboard] pushMetricsRemoved: container_id not found: " << container_id << "\n";
             data_updated_ = false;
         }
     }
     data_cv_.notify_one();
 }
References CM_LOG_INFO.
start()
void MonitorDashboard::start ()
Starts the dashboard UI thread.
Definition at line 88 of file monitor_dashboard.cpp.
{
     if (!running_) {
         running_ = true;
         worker_ = std::thread(&MonitorDashboard::run, this);
     }
 }
Referenced by main().
stop()
void MonitorDashboard::stop ()
Stops the dashboard UI thread.
Definition at line 98 of file monitor_dashboard.cpp.
{
     running_ = false;
     data_cv_.notify_one();
     if (worker_.joinable()) {
         worker_.join();
     }
 }
Referenced by main(), and ~MonitorDashboard().
The documentation for this class was generated from the following files:
ui/inc/monitor_dashboard.hpp
ui/src/monitor_dashboard.cpp