Container Monitor: ConfigParser Class Reference
ConfigParser Class Reference
Parses key-value configuration files and provides access to configuration parameters.
#include <config_parser.hpp>
Public Member Functions
bool load (std::string_view filename)
Loads configuration parameters from a file.
std::string get (std::string_view key, std::string_view default_val="") const
Gets a string value for a given key.
int getInt (std::string_view key, int default_val=0) const
Gets an integer value for a given key.
double getDouble (std::string_view key, double default_val=0.0) const
Gets a double value for a given key.
bool getBool (std::string_view key, bool default_val=false) const
Gets a boolean value for a given key.
MonitorConfig toMonitorConfig () const
Converts loaded parameters to a MonitorConfig struct.
void printConfig (const MonitorConfig &cfg) const
Prints the loaded configuration to the log.
Detailed Description
Parses key-value configuration files and provides access to configuration parameters.
Supports retrieval of string, integer, double, and boolean values, and conversion to MonitorConfig.
Definition at line 18 of file config_parser.hpp.
Member Function Documentation
get()
std::string ConfigParser::get (std::string_view key, std::string_view default_val = "") const
Gets a string value for a given key.
Parameters
key Configuration key.
default_val Default value if key is not found.
Returns
Value as string.
Definition at line 38 of file config_parser.cpp.
{
     auto it = params_.find(std::string(key));
     return it != params_.end() ? it->second : std::string(default_val);
 }
Referenced by getBool(), getDouble(), getInt(), and toMonitorConfig().
getBool()
bool ConfigParser::getBool (std::string_view key, bool default_val = false) const
Gets a boolean value for a given key.
Parameters
key Configuration key.
default_val Default value if key is not found or conversion fails.
Returns
Value as bool.
Definition at line 71 of file config_parser.cpp.
{
     auto val = get(key, "");
     if (val == "true" || val == "1") return true;
     if (val == "false" || val == "0") return false;
     return default_val;
 }
References get().
Referenced by toMonitorConfig().
getDouble()
double ConfigParser::getDouble (std::string_view key, double default_val = 0.0) const
Gets a double value for a given key.
Parameters
key Configuration key.
default_val Default value if key is not found or conversion fails.
Returns
Value as double.
Definition at line 60 of file config_parser.cpp.
{
     auto val = get(key, "");
     try { return std::stod(val); } catch (...) { return default_val; }
 }
References get().
Referenced by toMonitorConfig().
getInt()
int ConfigParser::getInt (std::string_view key, int default_val = 0) const
Gets an integer value for a given key.
Parameters
key Configuration key.
default_val Default value if key is not found or conversion fails.
Returns
Value as int.
Definition at line 49 of file config_parser.cpp.
{
     auto val = get(key, "");
     try { return std::stoi(val); } catch (...) { return default_val; }
 }
References get().
Referenced by toMonitorConfig().
load()
bool ConfigParser::load (std::string_view filename)
Loads configuration parameters from a file.
Parameters
filename Path to the configuration file.
Returns
True if loading was successful, false otherwise.
Definition at line 17 of file config_parser.cpp.
{
     std::ifstream file{std::string(filename)};
     if (!file.is_open()) return false;
     std::string line;
     while (std::getline(file, line)) {
         if (line.empty() || line[0] == '#') continue;
         auto pos = line.find('=');
         if (pos == std::string::npos) continue;
         std::string key = line.substr(0, pos);
         std::string val = line.substr(pos + 1);
         params_[key] = val;
     }
     return true;
 }
Referenced by Initializer::parseConfig().
printConfig()
void ConfigParser::printConfig (const MonitorConfig & cfg) const
Prints the loaded configuration to the log.
Parameters
cfg MonitorConfig object to print.
Definition at line 105 of file config_parser.cpp.
{
     CM_LOG_INFO << "Container Monitor started.\n";
     CM_LOG_INFO << "Runtime: " << cfg.runtime << "\n";
     CM_LOG_INFO << "Resource sampling interval: " << cfg.resource_sampling_interval_ms << " ms\n";
     CM_LOG_INFO << "Container event refresh interval: " << cfg.container_event_refresh_interval_ms << " ms\n";
     CM_LOG_INFO << "DB Path: " << cfg.db_path << "\n";
     CM_LOG_INFO << "UI Enabled: " << (cfg.ui_enabled ? "true" : "false") << "\n";
     CM_LOG_INFO << "Batch Size: " << cfg.batch_size << "\n";
     CM_LOG_INFO << "Alert thresholds: warning=" << cfg.alert_warning
                 << ", critical=" << cfg.alert_critical << "\n";
     CM_LOG_INFO << "Thread count: " << cfg.thread_count << "\n";
     CM_LOG_INFO << "Thread capacity: " << cfg.thread_capacity << "\n";
     CM_LOG_INFO << "File Export Path: " << cfg.file_export_folder_path << "\n";
     CM_LOG_INFO << "UI Refresh Interval: " << cfg.ui_refresh_interval_ms << " ms\n";
 }
References MonitorConfig::alert_critical, MonitorConfig::alert_warning, MonitorConfig::batch_size, CM_LOG_INFO, MonitorConfig::container_event_refresh_interval_ms, MonitorConfig::db_path, MonitorConfig::file_export_folder_path, MonitorConfig::resource_sampling_interval_ms, MonitorConfig::runtime, MonitorConfig::thread_capacity, MonitorConfig::thread_count, MonitorConfig::ui_enabled, and MonitorConfig::ui_refresh_interval_ms.
Referenced by Initializer::parseConfig().
toMonitorConfig()
MonitorConfig ConfigParser::toMonitorConfig () const
Converts loaded parameters to a MonitorConfig struct.
Returns
MonitorConfig object.
Definition at line 82 of file config_parser.cpp.
{
     MonitorConfig cfg;
     cfg.runtime                             = get(KEY_RUNTIME, DEFAULT_RUNTIME);
     cfg.cgroup                              = get(KEY_CGROUP, DEFAULT_CGROUP);
     cfg.database                            = get(KEY_DATABASE, DEFAULT_DATABASE);
     cfg.resource_sampling_interval_ms       = getInt(KEY_RESOURCE_SAMPLING_INTERVAL_MS, DEFAULT_RESOURCE_SAMPLING_INTERVAL_MS);
     cfg.container_event_refresh_interval_ms = getInt(KEY_CONTAINER_EVENT_REFRESH_INTERVAL_MS, DEFAULT_CONTAINER_EVENT_REFRESH_INTERVAL_MS);
     cfg.db_path                             = get(KEY_DB_PATH, DEFAULT_DB_PATH);
     cfg.ui_enabled                          = getBool(KEY_UI_ENABLED, DEFAULT_UI_ENABLED);
     cfg.batch_size                          = getInt(KEY_BATCH_SIZE, DEFAULT_BATCH_SIZE);
     cfg.alert_warning                       = getDouble(KEY_ALERT_WARNING, DEFAULT_ALERT_WARNING);
     cfg.alert_critical                      = getDouble(KEY_ALERT_CRITICAL, DEFAULT_ALERT_CRITICAL);
     cfg.thread_count                        = getInt(KEY_THREAD_COUNT, DEFAULT_THREAD_COUNT);
     cfg.thread_capacity                     = getInt(KEY_THREAD_CAPACITY, DEFAULT_THREAD_CAPACITY);
     cfg.file_export_folder_path             = get(KEY_FILE_EXPORT_FOLDER_PATH, DEFAULT_FILE_EXPORT_FOLDER_PATH);
     cfg.ui_refresh_interval_ms              = getInt(KEY_UI_REFRESH_INTERVAL_MS, DEFAULT_UI_REFRESH_INTERVAL_MS);
     return cfg;
 }
References MonitorConfig::alert_critical, MonitorConfig::alert_warning, MonitorConfig::batch_size, MonitorConfig::cgroup, MonitorConfig::container_event_refresh_interval_ms, MonitorConfig::database, MonitorConfig::db_path, DEFAULT_ALERT_CRITICAL, DEFAULT_ALERT_WARNING, DEFAULT_BATCH_SIZE, DEFAULT_CGROUP, DEFAULT_CONTAINER_EVENT_REFRESH_INTERVAL_MS, DEFAULT_DATABASE, DEFAULT_DB_PATH, DEFAULT_FILE_EXPORT_FOLDER_PATH, DEFAULT_RESOURCE_SAMPLING_INTERVAL_MS, DEFAULT_RUNTIME, DEFAULT_THREAD_CAPACITY, DEFAULT_THREAD_COUNT, DEFAULT_UI_ENABLED, DEFAULT_UI_REFRESH_INTERVAL_MS, MonitorConfig::file_export_folder_path, get(), getBool(), getDouble(), getInt(), KEY_ALERT_CRITICAL, KEY_ALERT_WARNING, KEY_BATCH_SIZE, KEY_CGROUP, KEY_CONTAINER_EVENT_REFRESH_INTERVAL_MS, KEY_DATABASE, KEY_DB_PATH, KEY_FILE_EXPORT_FOLDER_PATH, KEY_RESOURCE_SAMPLING_INTERVAL_MS, KEY_RUNTIME, KEY_THREAD_CAPACITY, KEY_THREAD_COUNT, KEY_UI_ENABLED, KEY_UI_REFRESH_INTERVAL_MS, MonitorConfig::resource_sampling_interval_ms, MonitorConfig::runtime, MonitorConfig::thread_capacity, MonitorConfig::thread_count, MonitorConfig::ui_enabled, and MonitorConfig::ui_refresh_interval_ms.
Referenced by Initializer::parseConfig().
The documentation for this class was generated from the following files:
utils/inc/config_parser.hpp
utils/src/config_parser.cpp