Container Monitor: Initializer Class Reference
Initializer Class Reference
Provides static methods for initializing logging, configuration, message queues, and signal handlers.
#include <initializer.hpp>
Static Public Member Functions
static void initLogger (int argc, char *argv[], const MonitorConfig &cfg)
Initializes the glog logger.
static void unlinkMessageQueue ()
Unlinks the POSIX message queue used for metrics.
static MonitorConfig parseConfig ()
Parses the configuration file and returns a MonitorConfig object.
static void setupSignalHandlers (void(*handler)(int))
Sets up signal handlers for graceful shutdown.
Detailed Description
Provides static methods for initializing logging, configuration, message queues, and signal handlers.
Definition at line 13 of file initializer.hpp.
Member Function Documentation
initLogger()
void Initializer::initLogger (int argc, char * argv[], const MonitorConfig & cfg) static
Initializes the glog logger.
Parameters
argc Command-line argument count.
argv Command-line argument array.
cfg Monitor configuration.
Definition at line 19 of file initializer.cpp.
{
     google::InitGoogleLogging(argv[0]);
     // Optionally set FLAGS_log_dir, etc. from cfg
 }
Referenced by main().
parseConfig()
MonitorConfig Initializer::parseConfig () static
Parses the configuration file and returns a MonitorConfig object.
Returns
Parsed MonitorConfig.
Definition at line 40 of file initializer.cpp.
{
     ConfigParser parser;
     if (!parser.load(CONFIG_FILE_PATH)) {
         CM_LOG_FATAL << "Failed to load configuration file. Exiting application \n";
     }
     MonitorConfig cfg = parser.toMonitorConfig();
     parser.printConfig(cfg);
     return cfg;
 }
References CM_LOG_FATAL, CONFIG_FILE_PATH, ConfigParser::load(), ConfigParser::printConfig(), and ConfigParser::toMonitorConfig().
Referenced by main().
setupSignalHandlers()
void Initializer::setupSignalHandlers (void(*)(int) handler) static
Sets up signal handlers for graceful shutdown.
Parameters
handler Signal handler function pointer.
Definition at line 54 of file initializer.cpp.
{
     std::signal(SIGINT, handler);
     std::signal(SIGTERM, handler);
 }
Referenced by main().
unlinkMessageQueue()
void Initializer::unlinkMessageQueue () static
Unlinks the POSIX message queue used for metrics.
Definition at line 27 of file initializer.cpp.
{
     int unlink_result = mq_unlink(METRIC_MQ_NAME.data());
     if (unlink_result == 0) {
         CM_LOG_INFO << "[Main] Successfully unlinked message queue \n";
     } else {
         CM_LOG_ERROR << "[Main] mq_unlink failed: " << strerror(errno) << "\n";
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, and METRIC_MQ_NAME.
Referenced by main().
The documentation for this class was generated from the following files:
utils/inc/initializer.hpp
utils/src/initializer.cpp