Container Monitor: MetricsReader Class Reference
MetricsReader Class Reference
Reads resource usage metrics for containers and the host system.
#include <metrics_reader.hpp>
Public Member Functions
MetricsReader (const ContainerResourcePaths &paths, int num_cpus)
Constructs a MetricsReader for a specific container.
int getMemoryUsage ()
Gets the container's memory usage in megabytes.
int getPids ()
Gets the container's current pids count.
double getMemoryUsagePercent (const ContainerInfo &info)
Gets the container's memory usage as a percentage of its limit.
double getPidsPercent (const ContainerInfo &info)
Gets the container's pids usage as a percentage of its limit.
HostInfo getHostInfo ()
Gets host system information (CPU count, total memory).
double getHostCpuUsagePercentage ()
Gets host CPU usage percentage.
double getHostMemoryUsagePercent ()
Gets host memory usage percentage.
uint64_t readUintFromFile (const std::string &path)
Reads an unsigned integer value from a file.
Detailed Description
Reads resource usage metrics for containers and the host system.
Provides methods to read memory, pids, and CPU usage for containers, as well as host CPU and memory usage. Supports conversion to percentages.
Definition at line 17 of file metrics_reader.hpp.
Constructor & Destructor Documentation
MetricsReader()
MetricsReader::MetricsReader (const ContainerResourcePaths & paths, int num_cpus)
Constructs a MetricsReader for a specific container.
Parameters
paths Resource file paths for the container.
num_cpus Number of CPUs on the host.
Definition at line 19 of file metrics_reader.cpp.
     : paths_(paths), num_cpus_(num_cpus)
 {}
Member Function Documentation
getHostCpuUsagePercentage()
double MetricsReader::getHostCpuUsagePercentage ()
Gets host CPU usage percentage.
Returns
CPU usage percent.
Definition at line 102 of file metrics_reader.cpp.
{
     std::ifstream file(PROC_STAT_PATH);
     std::string line;
     std::getline(file, line);
     uint64_t user, nice, system, idle, iowait, irq, softirq, steal;
     sscanf(line.c_str(), CPU_STAT_FORMAT,
            &user, &nice, &system, &idle, &iowait, &irq, &softirq, &steal);
     uint64_t total = user + nice + system + idle + iowait + irq + softirq + steal;
     uint64_t total_idle = idle + iowait;
     double usage = ZERO_PERCENT;
     if (last_total != 0 && last_idle != 0) {
         uint64_t delta_total = total - last_total;
         uint64_t delta_idle = total_idle - last_idle;
         usage = (double)(delta_total - delta_idle) / delta_total * PERCENT_FACTOR;
         usage = std::round(usage * PERCENT_FACTOR) / PERCENT_FACTOR;
     }
     last_total = total;
     last_idle = total_idle;
     return usage;
 }
References CPU_STAT_FORMAT, PERCENT_FACTOR, PROC_STAT_PATH, and ZERO_PERCENT.
getHostInfo()
HostInfo MetricsReader::getHostInfo ()
Gets host system information (CPU count, total memory).
Returns
HostInfo struct.
Definition at line 89 of file metrics_reader.cpp.
{
     HostInfo info;
     info.num_cpus = get_nprocs();
     struct sysinfo s_info;
     sysinfo(&s_info);
     info.total_memory_mb = s_info.totalram / (BYTES_PER_KILOBYTE * KILOBYTES_PER_MEGABYTE);
     return info;
 }
References BYTES_PER_KILOBYTE, KILOBYTES_PER_MEGABYTE, HostInfo::num_cpus, and HostInfo::total_memory_mb.
getHostMemoryUsagePercent()
double MetricsReader::getHostMemoryUsagePercent ()
Gets host memory usage percentage.
Returns
Memory usage percent.
Definition at line 128 of file metrics_reader.cpp.
{
     std::ifstream file(PROC_MEMINFO_PATH);
     std::string line;
     uint64_t mem_total = 0, mem_free = 0, buffers = 0, cached = 0;
     while (std::getline(file, line)) {
         if (line.find(MEMINFO_TOTAL) == 0)
             sscanf(line.c_str(), (std::string(MEMINFO_TOTAL) + " " + MEMINFO_FORMAT).c_str(), &mem_total);
         else if (line.find(MEMINFO_FREE) == 0)
             sscanf(line.c_str(), (std::string(MEMINFO_FREE) + " " + MEMINFO_FORMAT).c_str(), &mem_free);
         else if (line.find(MEMINFO_BUFFERS) == 0)
             sscanf(line.c_str(), (std::string(MEMINFO_BUFFERS) + " " + MEMINFO_FORMAT).c_str(), &buffers);
         else if (line.find(MEMINFO_CACHED) == 0)
             sscanf(line.c_str(), (std::string(MEMINFO_CACHED) + " " + MEMINFO_FORMAT).c_str(), &cached);
     }
     uint64_t used = mem_total - mem_free - buffers - cached;
     double percent = (mem_total > 0) ? ((double)used / mem_total * PERCENT_FACTOR) : ZERO_PERCENT;
     return std::round(percent * PERCENT_FACTOR) / PERCENT_FACTOR;
 }
References MEMINFO_BUFFERS, MEMINFO_CACHED, MEMINFO_FORMAT, MEMINFO_FREE, MEMINFO_TOTAL, PERCENT_FACTOR, PROC_MEMINFO_PATH, and ZERO_PERCENT.
getMemoryUsage()
int MetricsReader::getMemoryUsage ()
Gets the container's memory usage in megabytes.
Returns
Memory usage in MB.
Definition at line 41 of file metrics_reader.cpp.
{
     uint64_t mem_bytes = readUintFromFile(paths_.memory_path);
     return static_cast<int>(mem_bytes / (BYTES_PER_KILOBYTE * KILOBYTES_PER_MEGABYTE)); // MB
 }
References BYTES_PER_KILOBYTE, KILOBYTES_PER_MEGABYTE, ContainerResourcePaths::memory_path, and readUintFromFile().
Referenced by getMemoryUsagePercent().
getMemoryUsagePercent()
double MetricsReader::getMemoryUsagePercent (const ContainerInfo & info)
Gets the container's memory usage as a percentage of its limit.
Parameters
info ContainerInfo struct.
Returns
Memory usage percent.
Definition at line 68 of file metrics_reader.cpp.
{
     int mem_mb = getMemoryUsage();
     double percent = (info.memory_limit > 0) ? ((double)mem_mb / info.memory_limit * PERCENT_FACTOR) : ZERO_PERCENT;
     return round2(percent);
 }
References getMemoryUsage(), ContainerInfo::memory_limit, PERCENT_FACTOR, and ZERO_PERCENT.
getPids()
int MetricsReader::getPids ()
Gets the container's current pids count.
Returns
Number of pids.
Definition at line 50 of file metrics_reader.cpp.
{
     return static_cast<int>(readUintFromFile(paths_.pids_path));
 }
References ContainerResourcePaths::pids_path, and readUintFromFile().
Referenced by getPidsPercent().
getPidsPercent()
double MetricsReader::getPidsPercent (const ContainerInfo & info)
Gets the container's pids usage as a percentage of its limit.
Parameters
info ContainerInfo struct.
Returns
Pids usage percent.
Definition at line 79 of file metrics_reader.cpp.
{
     int pids = getPids();
     double percent = (info.pid_limit > 0) ? ((double)pids / info.pid_limit * PERCENT_FACTOR) : ZERO_PERCENT;
     return round2(percent);
 }
References getPids(), PERCENT_FACTOR, ContainerInfo::pid_limit, and ZERO_PERCENT.
readUintFromFile()
uint64_t MetricsReader::readUintFromFile (const std::string & path)
Reads an unsigned integer value from a file.
Parameters
path File path.
Returns
Value read from file.
Definition at line 28 of file metrics_reader.cpp.
{
     std::ifstream file(path);
     uint64_t value = 0;
     if (file.is_open()) {
         file >> value;
     }
     return value;
 }
Referenced by getMemoryUsage(), and getPids().
The documentation for this class was generated from the following files:
metrics_analyzer/inc/metrics_reader.hpp
metrics_analyzer/src/metrics_reader.cpp